### ISSUE TITLE
Incremental and absolute gating via Cerberus

### ISSUE THREAD

**Issue by dsvellal** [philips-software/cerberus#4]
For all the hounds, currently Cerberus only reports violations. Can we consider adding gating on the violations reported so that the # of violations can be configured & we can report a "pass" or a "fail" based on breach of threshold. 

Also to consider - relative gating, ie. if the previous violation count was x, and the threshold is set to x+5, if the subsequent violation count goes to x+3, we should have consider failing the build for this increase in threshold. If the threshold decreases, then automatically set the acceptable threshold to the lower value.

**Comment by dsvellal** [comment]
This request can also help us create a: pre-and-post metric snapshots, against which absolute and relative gatings can be applied on violations.

**Comment by aravind666** [comment]
I think this can go in the cerberus mode project ..once you create a project with detail explaination. Please create issues or stories for this enhancement .
