### ISSUE TITLE
Modes of operation with Cerberus

### ISSUE THREAD

**Issue by dsvellal** [philips-software/cerberus#5]
Consider different modes of operations for Cerberus: 
1. Report mode: This can be used for evidence collection, where Cerberus just reports out the identified violations. 
2. Benchmark mode: Set the thresholds of violation count to the current violation counts, this way if we'd want to run Cerberus on legacy code, we can set the thresholds based on the current state, and not allow an increase in incremental or absolute violations.
3. Suggestion mode: Where Cerberus not only identifies the violations but also suggests (context-sensitive) how to fix those violations as well. 
4. Enforce mode: Where Cerberus automatically makes the suggested changes and reports back what violation was corrected how!

User can choose the mode of operation of Cerberus via configurations!

**Comment by aravind666** [comment]
Can you create a project in github and split this task in the micro chunck of deliverables and their on the board . Here is an example project that I have created . 

https://github.com/philips-software/cerberus/projects/1
